### ISSUE TITLE
ETH Denver Event / Schedule Tracker 

### ISSUE THREAD

**Issue by robbiekruszynski** [rapid-eth/rapid-ideas#9]
**Track / List  Events for ETH Denver** 
- [ ] Feb 10th - fly in / set up.        
- [ ] Feb 11th - RAPID hang            
- [ ] Feb 12th -3Box event             
- [ ] Feb 13th - talks https://www.daofest.io/ | https://web3.sustainoss.org/                             
- [ ] Feb 14th - Hackathon                  
- [ ] Feb 15th - Hackathon           
- [ ] Feb 16th - Hackathon        

     
**Lodging** 

- [ ] Feb 10th   // AIR B&B
- [ ] Feb 11th    // AIR B&B
- [ ] Feb 12th   // AIR B&B
- [ ] Feb 13th  // AIR B&B
- [ ] Feb 14th  // AIR B&B
- [ ] Feb 15th  // Sheridan
- [ ] Feb 16th  // Sheridan
- [ ] Feb 17th  // Sheridan

**Comment by kamescg** [comment]
The 13th is the talks https://www.daofest.io/  | https://web3.sustainoss.org/

Hackathon starts on the 14th.

**Comment by robbiekruszynski** [comment]
@KamesCG Thank you!

**Comment by kamescg** [comment]
@orbro Thoughts on having a` One Million Developers Breakfast/Brunch` the day of the hackathon?

The event doesn't really start until later in the day and would be cool to meet up with all the developers and builders the morning of.
